defaults:
  actions:
    comment:
      bot_account: mergify-test4
pull_request_rules:
- actions:
    comment:
      message: Hello World!
  conditions:
  - base=20220811123617/test_comment_without_default_message/main
  name: comment without default message
