pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=main
  name: automatic merge
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  - current-datetime != XXXX-01-01T00:00/XXXX-01-01T23:59[Europe/Paris]
  name: default
  queue_conditions:
  - label=queue
