pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20240109153100/test_current_datetime_range_with_uncertain_year/main
  name: automatic merge
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  - current-datetime != 2024-01-01T00:00/2024-01-01T23:59[Europe/Paris]
  name: default
  queue_conditions:
  - label=queue
