defaults:
  actions:
    comment: {}
pull_request_rules:
- actions:
    comment:
      message: Hello World!
  conditions:
  - base=20220811125143/test_comment_without_default_message/main
  name: comment without default message
