pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - base=20221109205129/test_api_get_queues/main
  - label=queue
  name: queue
queue_rules:
- allow_inplace_checks: false
  conditions:
  - base=20221109205129/test_api_get_queues/main
  - check-success=continuous-integration/fake-ci
  name: foo
