pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230908092602/test_conflicts_with_pull_ahead/main
  - label=queue
  name: Queue on label
- actions:
    label:
      add:
      - queue-conflict
  conditions:
  - queue-dequeue-reason=conflict-with-pull-ahead
  name: Label queueu conflicts
queue_rules:
- allow_inplace_checks: false
  conditions: []
  name: default
