pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20221206145925/test_batch_max_failure_resolution_attempts/main
  - label=queue
  name: Merge priority high
queue_rules:
- batch_max_resolution_attempts: 0
  batch_size: 4
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
