pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240229130853/test_charly/main
  - label=queue
  name: Merge on queue label
queue_rules:
- conditions: []
  name: default
