pull_request_rules:
- actions:
    queue:
      method: merge
      name: default
      update_method: rebase
  conditions:
  - base=20240229133053/test_charly/main
  - label=queue
  name: Merge on queue label
queue_rules:
- conditions: []
  name: default
