pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20240109153648/test_current_datetime_range_with_uncertain_year/main
  name: automatic merge
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  - schedule != Mon-Mon 00:00-23:59[Europe/Paris]
  name: default
  queue_conditions:
  - label=queue
