"
queue_rules:
    - name: default
      queue_conditions:
        - label=queue
      merge_conditions:
        - and:
            - current-datetime != XXXX-01-01T00:00/XXXX-01-01T23:59[Europe/Paris]
            - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
pull_request_rules:
    - name: automatic merge
      conditions:
        - base={self.main_branch_name}
      actions:
        queue: {}
