pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20230728133247/test_checks_inject_queue_conditions_in_merge_conditions/main
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci-merge
  name: default
  queue_conditions:
  - status-success=continuous-integration/fake-ci-queue
