pull_request_rules:
- actions:
    queue:
      method: squash
      name: default
  conditions:
  - label=queue
  - base=20231004124252/test_branch_protection_linear_history/main
  name: merge
queue_rules:
- name: default
