pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230906124125/test_base_branch_conflict_during_check/main
  - label=queue
  name: Queue on label
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
