pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221019155253/test_required_status_checks_strict_incompatibility_with_spec_check/main
  name: Merge
queue_rules:
- allow_inplace_checks: true
  batch_size: 1
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 2
