
queue_rules:
    - name: default
      queue_conditions:
        - label=queue
      merge_conditions:
        - and:
            - not:
                - or:
                    - current-datetime = XXXX-01-01T00:00/XXXX-01-01T23:59[Europe/Paris]
                    - current-datetime = XXXX-05-01T00:00/XXXX-05-01T23:59[Europe/Paris]
                    - current-datetime = XXXX-05-08T00:00/XXXX-05-08T23:59[Europe/Paris]
                    - current-datetime = XXXX-07-14T00:00/XXXX-07-14T23:59[Europe/Paris]
                    - current-datetime = XXXX-08-15T00:00/XXXX-08-15T23:59[Europe/Paris]
                    - current-datetime = XXXX-11-01T00:00/XXXX-11-01T23:59[Europe/Paris]
                    - current-datetime = XXXX-11-11T00:00/XXXX-11-11T23:59[Europe/Paris]
                    - current-datetime = XXXX-12-25T00:00/XXXX-12-25T23:59[Europe/Paris]
            - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
pull_request_rules:
    - name: automatic merge
      conditions:
        - base=20240111081926/test_merge_condition_out_of_schedule/main
      actions:
        queue:
