
queue_rules:
  - name: default
    allow_inplace_checks: false
    merge_conditions:
      - check-success=continuous-integration/fake-ci
    queue_conditions:
      - check-success=continuous-integration/fake-ci
      - base=20240202160012/test_requeue_after_push/main
