partition_rules:
- fallback_partition: true
  name: fallback
- conditions:
  - files~=^source/go/
  name: go
- conditions:
  - files~=^source/infrastructure/
  name: infrastructure
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - label!=high-priority
  - base=20240905083509/test_anchorage/main
  - status-success=buildkite/anchorage
  name: Merge default
- actions:
    queue:
      name: high-priority
  conditions:
  - label=high-priority
  - base=20240905083509/test_anchorage/main
  name: Merge high-priority
queue_rules:
- merge_conditions:
  - status-success=buildkite/anchorage
  name: high-priority
  queue_conditions:
  - status-success=buildkite/anchorage
- batch_size: 4
  merge_conditions:
  - status-success=buildkite/anchorage
  name: default
  queue_conditions:
  - status-success=buildkite/anchorage
  speculative_checks: 8
