pull_request_rules:
- actions:
    queue:
      method: squash
      name: default
  conditions:
  - label=queue
  - base=20231004090302/test_branch_protection_linear_history/main
  name: merge
queue_rules:
- merge_method: squash
  name: default
