pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20240109154639/test_current_datetime_range_with_uncertain_year/main
  name: automatic merge
queue_rules:
- merge_conditions:
  - current-datetime != XXXX-01-01T00:00/XXXX-01-01T23:59[Europe/Paris]
  name: default
  queue_conditions:
  - label=queue
