pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - base=20230110153552/test_get_queue_pull_next_evaluation_at/main
  - label=queue
  name: queue
queue_rules:
- allow_inplace_checks: false
  conditions:
  - base=20230110153552/test_get_queue_pull_next_evaluation_at/main
  - check-success=continuous-integration/fake-ci
  - schedule=MON-FRI 12:00-15:00
  name: foo
