merge_protections:
- if:
  - base=20241023084105/test_merge_protections_queue_injection/main
  name: Applied rule
  success_conditions:
  - check-success=continuous-integration/fake-ci
- if:
  - base=some-other-branch
  name: Ignored rule
  success_conditions:
  - check-success=continuous-integration/another-ci
queue_rules:
- allow_inplace_checks: false
  batch_size: 2
  name: default
